package uz.mygift.base;

public interface BaseUrl {
    String PATH_ID = "/{id}";
    String PATH_USER_ID = "/{userId}";
    String USER = "/user";
    String LOG_ERROR="/log";
    String GENERATE_TOKEN = "/generate";
    String REFRESH = "/refresh";
    String CREATE = "/create";
    String UPDATE = "/update";
    String DOWNLOAD = "/download";
    String PREVIEW = "/preview";
    String FAVORITE = "/favorite";
    String DELETE = "/delete";
    String FIND = "/find";
    String GET_ALL = "/show";
    String VIEW = "/view";
    String BASKET = "/basket";
    String DISCOUNT = "/discount";
    String CATEGORY = "/category";
    String ABOUT_US = "/about/us";
    String SERVICE = "/service";
    String PARTNER = "/partner";
    String IMAGE = "/image";
    String TYPE = "/type";
    String PRODUCT = "/product";
    String INCREASE="/increase";
    String DECREASE="/decrease";
    String SIZE="/{size}";
    String PAGE="/{page}";
    String TIME="/time";
    String ALL="/all";
    String MONTH="/month";
    String WEEK="/week";
    String YEAR="/year";
    String DAY="/day";
    String REACTION="/reaction";
    String PATH_PRODUCT_ID="/{productId}";

    String REACTION_WEEK=REACTION+WEEK+PAGE+SIZE;
    String REACTION_MONTH=REACTION+MONTH+PAGE+SIZE;
    String REACTION_YEAR=REACTION+YEAR+PAGE+SIZE;
    String REACTION_PRODUCTS_WITH_USER_ID=REACTION+PRODUCT+PATH_USER_ID;
    String REACTION_ALL_TIME=REACTION+ALL+TIME+PAGE+SIZE;
    String REACTION_PRODUCTS=REACTION+PRODUCT;
    String CREATE_BY_ID=CREATE+PATH_ID;
    String CREATE_WHIT_PRODUCT_ID=CREATE+PATH_PRODUCT_ID;
    String PRODUCT_TYPE=PRODUCT+TYPE;
    String DOWNLOAD_BY_ID=DOWNLOAD+PATH_ID;
    String PREVIEW_BY_ID=PREVIEW+PATH_ID;
    String SERVICE_TYPE=SERVICE+TYPE;
    String REFRESH_TOKEN= GENERATE_TOKEN +REFRESH;
    String FIND_BY_ID = FIND + PATH_ID;
    String DELETE_BY_ID = DELETE + PATH_ID;
    String UPDATE_BY_ID = UPDATE + PATH_ID;
}
